<?php echo $this->flashMessages(); ?>
<div class="widget">
    <div class="widget-head">Instellingen</div>
    <div class="widget-content">
        <div class="padd">
            <ul class="nav nav-tabs" id="myTab">
                <li class="active"><a href="#Algemeen-ContentPane">Algemeen</a></li>
                <li><a href="#Plugins-ContentPane">Plugins</a></li>
                <li class="pull-right"><a href="#Manager-ContentPane">Manager</a></li>
            </ul>

            <?php
            $print = false;
            if ($print)
            {
                echo '<pre>';
                print_r($this->form);
                echo '</pre>';
            }
            else {
                ?>
                <div class="tab-content">
                    <form method="<?php echo $this->form->getMethod(); ?>" enctype="<?php echo $this->form->getEnctype(); ?>" action="<?php echo $this->form->getAction(); ?>" class="form-horizontal">
                        <?php echo $this->form; ?>
                    </form>
                </div>
            <?php
            }
            ?>
        </div>
    </div>

</div>


<script>
	$('#myTab a').click(function (e) {
		e.preventDefault();
		$(this).tab('show');
	})
</script>