<?php
    foreach (range(1, 5) as $i) {
        ?>
        <!-- Example row of columns -->
        <div class="row">
            <div class="col-md-8 grey-block">
                <h1>Nieuws item</h1>
                <p class="help-block">23-2-2014, Gepost door: Jon Doe</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Suspendisse nec egestas urna, sed pretium velit.
                    Nulla faucibus est pharetra, viverra magna sed, ullamcorper elit.
                    Fusce pellentesque convallis quam in posuere. Mauris fermentum tellus ac interdum sagittis.
                    <a href="#">Lees meer...</a>
                </p>
            </div>
        </div>
        <?php
    }
?>