<?php
	$settingModel = new Model_Setting();
	$this->headTitle($this->escape($settingModel->getSettings('siteSlogan')));
?>

<!-- Example row of columns -->
<div class="row">
    <div class="col-md-8">
        <h2>SOS Rommelmarkt</h2>
        <p>SOS Rommelmarkt is een kringloop-winkel waar ook mensen nieuwe kansen krijgen. Met de winst ondersteunt SOS kleinschalige projecten in de derde wereld.</p>
        <p class="text-right"><a class="btn btn-danger" href="pages/about.php" role="button">Naar Wat wij doen &raquo;</a></p>
    </div>
    <div class="col-md-4 text-center">
        <div class="panel panel-danger">
            <div class="panel-heading">
                Openingstijden
            </div>
            <div class="panel-body">
                <p>Maandag & zondag de hele dag gesloten.<br>
                    Elke andere dag geopend van 10:00 tot 17:00.</p>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-8">
        <section id="carousel">
            <div class="quote"><i class="fa fa-quote-left fa-3x"></i></div>
            <div class="carousel slide" id="fade-quote-carousel" data-ride="carousel" data-interval="8000">
                <!-- Carousel indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#fade-quote-carousel" data-slide-to="0" class="active"></li>
                    <li data-target="#fade-quote-carousel" data-slide-to="1"></li>
                    <li data-target="#fade-quote-carousel" data-slide-to="2"></li>
                </ol>
                <!-- Carousel items -->
                <div class="carousel-inner">
                    <div class="active item">
                        <blockquote>
                            <p><b>Duurzaam door hergebruik</b></p>
                            <p>Alles wat verkoopbaar is krijgt bij klanten een nieuw leven. Het restafval wordt gescheiden aangeleverd bij verwerkingsbedrijven.</p>
                        </blockquote>
                    </div>
                    <div class="item">
                        <blockquote>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem, veritatis nulla eum laudantium totam tempore optio doloremque laboriosam quas, quos eaque molestias odio aut eius animi. Impedit temporibus nisi accusamus.</p>
                        </blockquote>
                    </div>
                    <div class="item">
                        <blockquote>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem, veritatis nulla eum laudantium totam tempore optio doloremque laboriosam quas, quos eaque molestias odio aut eius animi. Impedit temporibus nisi accusamus.</p>
                        </blockquote>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <div class="col-md-4 text-center">
        <div class="panel panel-danger">
            <div class="panel-heading">
                Algemene informatie
            </div>
            <div class="panel-body">
                <p>SOS Rommelmarkt (Stichting Spoor 073)<br>
                    Ridderspoorstraat 2<br>
                    5212 XP 's-Hertogenbosch<br>
                    (073) 613 37 74<br><br>
                    <a href="mailto:info@sosrommelmarkt.nl">info@sosrommelmarkt.nl</a><br>
                    <a href="http://www.sosrommelmarkt.nl">www.sosrommelmarkt.nl</a></p>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-8">
        <hr>
        <h3>Laatste nieuws</h3>
        <div class="row">
            <div class="col-md-12">
                <p><strong>SOS Rommelmarkt nu actief op boekwinkeltjes.nl!</strong></p>
                <p>SOS Rommelmarkt heeft een webshop geopend op boekwinkeltjes.nl.<br/>
                    Onze online boekwinkel is te zien door de onderstaande link te volgen.<br><a target="_blank" href="http://boekwinkeltjes.nl/bwzoeken.php?bwID=22317">Boekwinkeltjes.nl</a><br><br><a href="#">Lees meer</a></p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <p><strong>Geslaagde opening</strong></p>
                <p>
                    Gisteren is ons nieuwe pand feestelijk in gebruik genomen. Wethouder Geert Snijders, onze voorzitter Jetty Eugster en Bart Eigeman, voorzitter van het PUB kregen van medewerkers delen van een sleutel.  Samen konden ze de sleutel compleet maken, en na de woorden van wethouder Geert Snijders werd het pand dan ook officieel geopend.<br><br>
                    <a href="#">Lees meer</a>
                </p>
            </div>
        </div>
        <div class="row">
            <p class="text-right"><a class="btn btn-danger" href="pages/news.php" role="button">Naar Nieuws &raquo;</a></p>
        </div>
    </div>
    <div class="col-md-4 text-center">
        <hr>
        <div class="row">
            <h3>Vitrine</h3>
        </div>
        <div class="row">
            <img src="<?php echo $this->baseUrl('public/img/tile.png'); ?>" width="150px" height="200px" alt="Veiling product">
        </div>
        <div class="row">
            <p><b>Vitrine product van de maand!</b><br><br>
                Deze einddatum voor de huidige producten in de vitrine is:<br>
                <b>28 maart</b>.</p>
        </div>
        <div class="row">
            <p><a class="btn btn-danger" href="pages/auction.php" role="button">Naar Vitrines &raquo;</a></p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-8 text-center">
        <hr>
        <div class="row">
            <h3>Nieuwe artikelen</h3>
        </div>
        <div class="row">
            <div class="container">
                <div class="col-md-2 cursor-pointer">
                    <img src="<?php echo $this->baseUrl('public/img/tile.png'); ?>" width="100px" height="100px" alt="Steigerhout tafel">
                    <p><b>Steigerhout tafel</b></p>
                    <p>Robuuste tafel van landelijk steigerhout. Nu verlaagd in prijs!</p>
                </div>
                <div class="col-md-2 cursor-pointer">
                    <img src="<?php echo $this->baseUrl('public/img/tile.png'); ?>" width="100px" height="100px" alt="Televisie">
                    <p><b>Televisie</b></p>
                    <p>Deze televisie is zo goed als nieuw. Beschikt over een 1080p resolutie.</p>
                </div>
                <div class="col-md-2 cursor-pointer">
                    <img src="<?php echo $this->baseUrl('public/img/tile.png'); ?>" width="100px" height="100px" alt="Retro sofa">
                    <p><b>Retro sofa</b></p>
                    <p>Deens design. geïnspireerd op de 70'er jaren. Een leuke verschijning.</p>
                </div>
                <div class="col-md-2 cursor-pointer">
                    <img src="<?php echo $this->baseUrl('public/img/tile.png'); ?>" width="100px" height="100px" alt="Gitaar">
                    <p><b>Akoestische gitaar</b></p>
                    <p>Met deze gitaar steelt u de show bij menig 'kampvuurfeestje'!</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="container">
                <div class="col-md-2 cursor-pointer">
                    <img src="<?php echo $this->baseUrl('public/img/tile.png'); ?>" width="100px" height="100px" alt="Steigerhout tafel">
                    <p><b>Steigerhout tafel</b></p>
                    <p>Robuuste tafel van landelijk steigerhout. Nu verlaagd in prijs!</p>
                </div>
                <div class="col-md-2 cursor-pointer">
                    <img src="<?php echo $this->baseUrl('public/img/tile.png'); ?>" width="100px" height="100px" alt="Televisie">
                    <p><b>Televisie</b></p>
                    <p>Deze televisie is zo goed als nieuw. Beschikt over een 1080p resolutie.</p>
                </div>
                <div class="col-md-2 cursor-pointer">
                    <img src="<?php echo $this->baseUrl('public/img/tile.png'); ?>" width="100px" height="100px" alt="Retro sofa">
                    <p><b>Retro sofa</b></p>
                    <p>Deens design. geïnspireerd op de 70'er jaren. Een leuke verschijning.</p>
                </div>
                <div class="col-md-2 cursor-pointer">
                    <img src="<?php echo $this->baseUrl('public/img/tile.png'); ?>" width="100px" height="100px" alt="Gitaar">
                    <p><b>Akoestische gitaar</b></p>
                    <p>Met deze gitaar steelt u de show bij menig 'kampvuurfeestje'!</p>
                </div>
            </div>
        </div>
        <div class="row">
            <p class="text-right"><a class="btn btn-danger" href="pages/shop.php" role="button">Naar webshop &raquo;</a></p>
        </div>
    </div>
    <div class="col-md-4 text-center">
        <hr>
        <div class="row">
            <h3>Handige links</h3>
            <p>Hieronder zijn een aantal handige links te vinden</p>
        </div>
        <hr>
        <div class="row">
            <p><a class="hvr-grow" target="_blank" href="http://boekwinkeltjes.nl/bwzoeken.php?bwID=22317"><img src="<?php echo $this->baseUrl('public/img/Boekwinkeltje_Logo.png'); ?>" width="65%"></a></p>
        </div>
        <hr>
        <div class="row">
            <p><a class="hvr-grow" target="_blank" href="http://www.deverscholenstad.nl/"><img src="<?php echo $this->baseUrl('public/img/Verscholenstad_Logo.png'); ?>" width="65%"></a></p>
        </div>
        <hr>
        <div class="row">
            <p><a class="hvr-grow" target="_blank" href="https://www.facebook.com/pages/SOS-rommelmarkt/359481534072417"><i class="fa fa-facebook-official fa-5x"></i></a></p>
        </div>
        <hr>
    </div>
</div>