<?php
	$settingModel = new Model_Setting();
	$this->headTitle($this->escape($settingModel->getSettings('siteSlogan')));
?>

<!-- Example row of columns -->
<div class="row">
    <div class="col-md-8">
        <h2>SOS Rommelmarkt</h2>
        <p>Welkom bij dé webshop voor Nutella Hazelnootpasta en Calvé Pindakaas!
            Alleen hier vindt u het lekkerste broodbeleg voor de beste prijzen!</p>
        <p class="text-right"><a class="btn btn-danger" href="pages/about.php" role="button">Naar de winkel &raquo;</a></p>
    </div>
</div>
</div>