<?php 
	$this->headTitle('Contact');
?>

<h1 class="titel">Contact</h1>
<div class="kaderBlauw">
	<?php echo $this->flashMessages(); ?>
	<section class="links">
		<form method="<?php echo $this->form->getMethod(); ?>" enctype="<?php echo $this->form->getEnctype(); ?>" action="<?php echo $this->form->getAction(); ?>">
			<?php echo $this->form; ?>
		</form>
		<div class="clear"></div>
	</section>
	<section class="rechts">
		
	</section>
	<div class="clear"></div>
</div>