<?php echo $this->flashMessages(); ?>
<div class="widget">
    <div class="widget-head">Beheer groepen</div>
    <div class="widget-content">
        <div class="padd">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Groep</th>
                    <th>Permissies</th>
                    <th>Actie</th>
                </tr>
                </thead>
                <caption class="text-left muted">
                    Beheer hier de groepen die kunnen worden toegewezen aan gebruikers.<br />
                    De toegewezen groep bepaald wat een gebruiker mag zien en doen.
                </caption>
                <tbody>
                <?php
                foreach($this->roles as $role)
                {
                    echo '<tr>
				<td><a href="' . $this->url(array('id' => $role->getId()), 'permission-admin-role-edit') . '">' . $this->escape($role->getName()) . '</a></td>
				<td><a href="' . $this->url(array('roleId' => $role->getId()), 'permission-admin-permission-edit') . '">Permissies</a></td>
				<td>' . ((!array_key_exists($role->getId(), $role->getReadOnly())) ? '<a href="' . $this->url(array('id' => $role->getId()), 'permission-admin-role-delete') . '" class="confirmDelete">Verwijderen</a>' : '') . '</td>
			</tr>';
                }
                ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="widget-foot">
        <?php echo $this->paginationControl($this->roles, 'Sliding', '_pagination.phtml'); ?>
    </div>
</div>