<?php

/**
 * @author Mark van Kleef (mkleef@avans.nl)
 * @copyright Copyright (c) 2015, Avans Hogeschool - All rights reserved
 * @version 1.0.0
 */

$html = array('<ul class="nav navbar-nav">');

foreach($this->container as $page)
{
	// visibility of the page
    if(!$page->isVisible() || !$this->navigation()->accept($page))
    {
        continue;
    }

    // dropdown
    $dropdown = !empty($page->pages);

    // header
    $html[] = '<li' . ($dropdown ? ' class="dropdown"' : '') . '>
    	<a href="' . ($dropdown ? '#' : $page->getHref()) . '" 
    		' . ($dropdown ? ' class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"' : '') . '>'
            . $page->getLabel() . ($dropdown ? '<span class="caret"></span>' : '') .  '</a>';
    
    if(!$dropdown)
    {
        $html[] = '</li>';
        continue;
    }

    $html[] = '<ul class="dropdown-menu" role="menu">';

    foreach($page->pages as $subpage)
    {
        // visibility of the sub-page
        if(!$subpage->isVisible() || !$this->navigation()->accept($subpage))
        {
            continue;
        }

        $html[] = '<li' . ( '' /* $subpage->isActive(true) ? ' class="active"' : ''*/) . '>
        	<a href="' . $subpage->getHref() . '">';

        /*if($subpage->get('icon'))
        {
            $html[] = '<i class="icon-' . $subpage->get('icon') . '"></i>';
        }*/

        $html[] = $subpage->getLabel() . '</a></li>';
    }

    $html[] = '</ul></li>';
}

$html[] = '</ul>';

echo join(PHP_EOL, $html);

?>